INSERT INTO recipe (category_id, recipe_name, image)
VALUES (2, 'Bacon, Egg, and Cheese Roll Ups' , 'http://tinyimg.io/i/PBTbbbc.jpg');
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('6 Large Eggs', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 tbsp Milk', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/4 tsp Garlic Powder', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('Kosher Salt', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('freshly ground Black Pepper', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 tbsp Butter', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 tbsp finely chopped Chives', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('12 Slices Bacon', 18);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 Cups of Shredded Cheddar', 18);
INSERT INTO directions (recipe_id, step_directions) VALUES (18, 'In a large bowl, whisk together eggs, milk, and garlic powder and season with salt and pepper.');
INSERT INTO directions (recipe_id, step_directions) VALUES (18, 'In a nonstick skillet over medium heat, melt butter. Add eggs and scramble, 3 minutes, then stir in chives.');
INSERT INTO directions (recipe_id, step_directions) VALUES (18, 'On a cutting board, lay out three strips of bacon. Sprinkle the bottom third with cheddar and top with a large spoonful of scrambled eggs. Roll up tightly. Repeat with remaining cheese and eggs.');
INSERT INTO directions (recipe_id, step_directions) VALUES (18, 'Return skillet to heat and add bacon roll-ups seam side down. Cook until crispy on all sides, then transfer to a paper towel-lined plate until ready to serve.');
INSERT INTO recipe (category_id, recipe_name, image)
VALUES (2, 'Burrito Zucchini Boats', 'http://tinyimg.io/i/PBTbbbc.jpg');
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('3 Zucchini halved lengthwise', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 tbsp Extra Virgin Olive Oil divided', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('Kosher Salt', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 cups Shredded Cheddar', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('Freshly Ground Black Pepper', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/2 Onion chopped', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 cloves Garlic minced', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/2 tsp Chili Powder', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/2 tsp ground Cumin', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/4 tsp Paprika', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/2 cups Black Beans', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/2 cups chopped Cherry Tomatoes', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/2 cups Corn', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 cup Shredded Cheddar', 19);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 cup Shredded Monterey Jack', 19);
INSERT INTO directions (recipe_id, step_directions) VALUES (19, 'Preheat oven to 350°. Score zucchini and scoop out insides reserving them for later. Place zucchini halves cut side-up into bottom of 9x13 baking dish and drizzle with 1 tablespoon oil. Season with salt and pepper. Bake until zucchini turns bright green and is just beginning to soften 10 minutes.');
INSERT INTO directions (recipe_id, step_directions) VALUES (19, 'In a large skillet over medium heat, heat oil. Add onion and reserved zucchini and cook until soft, about 5 minutes. Stir in garlic and cook until fragrant, about 1 minute more. Add ground beef, breaking up the meat with a wooden spoon. Cook until beef is no longer pink, about 6 minutes. Drain fat.');
INSERT INTO directions (recipe_id, step_directions) VALUES (19, 'Stir in chili powder, cumin, and paprika, then season with salt and pepper. Stir in black beans, cherry tomatoes, and corn.');
INSERT INTO directions (recipe_id, step_directions) VALUES (19, 'Spoon beef mixture into zucchini then top with cheeses. Bake until zucchini is just tender and cheeses are melted, about 15 minutes. Garnish with cilantro before serving.');
INSERT INTO recipe (category_id, recipe_name, image)
VALUES (3, 'Hoisin Glazed Pork Chops', 'http://tinyimg.io/i/5hx3jBM.JPG');
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('4 Pork chops boneless about 2 lbs', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('3/4 tsp Salt', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 tbsp Sesame oil', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 Garlic cloves minced', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 tsp Ginger minced', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1/3 cup Hoisin sauce', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 tbsp Rice vinegar', 20);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('2 tbsp Water', 20);
INSERT INTO directions (recipe_id, step_directions) VALUES (20, '1. In a small sauce pan set over medium heat. Simmer the garlic,ginger, hoisin, rice vinegar and water, whisking occasionally until the mixture is fully combined, about 4 minutes. Set aside.');
INSERT INTO directions (recipe_id, step_directions) VALUES (20, 'Lightly salt pork chops. Heat the sesame oil in a large skillet overhigh heat. Once oil is smoking, place the pork chops in theskillet, cook without turning until well browned, 3 to 4 minutes on each side. When an instant read thermometer inserted into the thickest part registers 135°F, remove the pork chops from the pan.Transfer to a cutting board and let rest 5 minutes.');
INSERT INTO directions (recipe_id, step_directions) VALUES (20, 'Serve with hoisin sauce drizzled over top.');
INSERT INTO recipe (category_id, recipe_name, image)
VALUES (3, 'Grilled Five Spice Flank Steak', 'http://tinyimg.io/i/9ldTwda.jpg');
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1.5 lb Flank Steak', 21);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 tsp Salt', 21);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('½ cup Hoisin Sauce', 21);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 tbsp Chinese 5 Spice', 21);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1bag asian salad kit grab one with sesamedressing if possible)', 21);
INSERT INTO ingredient (ingredient_name, recipe_id) VALUES ('1 tbsp Sesame seeds optional', 21);
INSERT INTO directions (recipe_id, step_directions) VALUES (21, ' Lightly score the surface of the flank steak with a sharp knife.Sprinkle it with salt on both sides.');
INSERT INTO directions (recipe_id, step_directions) VALUES (21, 'Mix the hoisin and Chinese five spice in a small bowl. Pour over the flank steak on a rimmed baking sheet and coat it entirely. Marinate in the fridge for at least one hour ');
INSERT INTO directions (recipe_id, step_directions) VALUES (21,'Heat grill to 350°F. Cook the flank steak on both sides to your desired doneness. Normally about 6 minutes per side for medium rare. We suggest using an instant read thermometer.');
INSERT INTO directions (recipe_id, step_directions) VALUES (21, 'Rest the meat for 5 minutes before thinly slicing against thegrain.');
INSERT INTO directions (recipe_id, step_directions) VALUES (21, 'Toss the salad and all the fixings in a bowl. Serve the steak with extra hoisin sauce over the salad sprinkled with sesame seeds.');